# Add configuration values here, as shown below.
#
bluemix_url: "https://gateway.watsonplatform.net/personality-insights/api"
bluemix_username: "bfa27aa8-100e-41b9-892a-b62e65c63e22"
bluemix_password: "lIA8IzGzX6Av"

#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
