development: 
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= Figaro.env.elephant_uri %>

production: 
  adapter: postgresql
  database: phhjwhfx
  encoding: unicode
  pool: 5
  url: <%= Figaro.env.elephant_uri %>