development: 
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: test<%=ENV['TEST_ENV_NUMBER']%>
  
# No need to define production if using Heroku Postgres
# production: 
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   url: <%= Figaro.env.elephant_uri %>